### PR TITLE
Job Posting Functionality Implementation

### LINKED ISSUE #37: Implement Job Posting Functionality
#### Issue Description:
As a client, I want to be able to post new job listings on the platform so that freelancers can view and apply for them. This functionality should ensure that all necessary job details are collected and stored in the database.

#### Tasks:
1. Create an endpoint in the **JobController** for clients to post new job listings.
2. Define the required fields for job postings, aligning with the database schema:
   - **client_id**: ID of the client (automatically derived from the authenticated user's context)
   - **title**: Job title (required)
   - **description**: Job description (required)
   - **budget**: Job budget (optional)
   - **job_type**: Job type (must be either "Hourly" or "Fixed", required)
   - **status**: Initial status of the job (default to "Open", required)
   - **created_at**: Timestamp (automatically set to the current timestamp)
3. Implement validation to ensure all required fields are provided and meet the necessary criteria.
4. Store the job details in the database using the defined schema.
5. Implement error handling to return meaningful messages for invalid data.

#### Acceptance Criteria:
- [ ] Clients should be able to make a `POST` request to `/jobs` to create a new job listing.
- [ ] Return **201 Created** if the job is posted successfully.
- [ ] Return **400 Bad Request** if any required fields are missing or invalid.
- [ ] Ensure proper error handling and validation messages.
- [ ] Job postings should be stored in the database and retrievable through the **Get All Jobs** endpoint.

#### Endpoint Specification:
- **Method**: `POST`
- **URL**: `/jobs`
- **Request Body Example**:
    ```json
    {
      "title": "Web Developer Needed",
      "description": "Looking for an experienced web developer to create a website.",
      "budget": 500.00,
      "job_type": "Fixed"
    }
    ```
- **Response Example** (Success - 201 Created):
    ```json
    {
      "message": "Job posted successfully",
      "jobId": 12345
    }
    ```
- **Response Example** (Invalid Data - 400):
    ```json
    {
      "error": "Job title is required"
    }
    ```

### LINKED ISSUE #51: SQL migration file does not follow the Flyway filename convention
image

The file `V5_Create_user_profile_to_all_inserted_users.sql` does not follow the correct naming convention. 

Flyway expects migration files to follow a specific naming pattern: `V<version>__<description>.sql`.

The correct format should use double underscores (`__`) after the version number.

### PR DESCRIPTION
**Pull request by AhmedFatthy1040**
# Feature: Job Posting Functionality

**Closes #37**
**Closes #51**

This PR introduces the core functionality for job posting, including:

- **Job Entity:** Defines the structure of a job.
- **Job Repository:** Provides data access for jobs.
- **Job Service:** Handles job-related business logic.
- **Job Controller:** Exposes REST endpoints for job management.
- **Job DTO:** Defines data transfer objects for jobs.
- **Security:** Implements role-based access control for job operations.

**To test:**

1. Start the application.
2. Send a POST request to `/api/jobs/post` with a valid JSON payload.
3. Verify job creation and retrieval.

**Please review the code changes and unit tests.**

### CODE REVIEW

**Review by AhmedMohamedAbdelaty — CHANGES_REQUESTED** [review]
Great job!

**Review by AhmedMohamedAbdelaty — CHANGES_REQUESTED** [review]
When creating a Job, the `jobId`, `status`, and `createdAt` fields are not needed in the POST request body. Could you please create a separate DTO for creating a Job that excludes these fields? Thanks!

Also, the `createdAt` field is set to null; please make sure it is initialized.

**Review by AhmedYahia74 — COMMENTED** [review]
In the job post, the client can add required skills for the job, but you missed implementing that

**Comment by AhmedFatthy1040** [comment]
> In the job post, the client can add required skills for the job, but you missed implementing that

I think adding the required skills should be implemented in a separate endpoint to avoid complexity and keep the responsibilities of each API call clear and manageable. This approach would make it easier to maintain and extend the functionality if needed.

**Comment by AhmedMohamedAbdelaty** [comment]
> I think adding the required skills should be implemented in a separate endpoint to avoid complexity and keep the responsibilities of each API call clear and manageable.

I think it’d be a good idea to keep the required skills in the same endpoint. Splitting it into a separate endpoint could make things unnecessarily complicated.

We could let clients select from a list of matching skills, and if they don’t find what they need, they can create a new skill on the spot. This way, we’ll also reduce the number of API calls.

**Comment by AhmedFatthy1040** [comment]
> > I think adding the required skills should be implemented in a separate endpoint to avoid complexity and keep the responsibilities of each API call clear and manageable.
> 
> I think it’d be a good idea to keep the required skills in the same endpoint. Splitting it into a separate endpoint could make things unnecessarily complicated.
> 
> We could let clients select from a list of matching skills, and if they don’t find what they need, they can create a new skill on the spot. This way, we’ll also reduce the number of API calls.

ok, i will implement it. 
GE7ZklXXcAAY3Ug

**Comment by AhmedFatthy1040** [comment]
Done @AhmedMohamedAbdelaty  @AhmedYahia74

**Review by AhmedYahia74 — APPROVED** [review]

**Review by AhmedMohamedAbdelaty — APPROVED** [review]
LGTM

**Pull request merged**
